//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ADHDTech.CiscoCrypt
{
    public class platformConfigXML
    {

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class PlatformData
        {

            private string versionField;

            private InstallType[] installTypeField;

            private ProductDeployment[] productDeploymentField;

            private PlatformConfigurationDone[] platformConfigurationDoneField;

            private PreLoadedSoftware[] preLoadedSoftwareField;

            private LocalHostName[] localHostNameField;

            private LocalHostNICAuto[] localHostNICAutoField;

            private ChangeMTUSize[] changeMTUSizeField;

            private LocalHostDHCP[] localHostDHCPField;

            private LocalHostDomain[] localHostDomainField;

            private LocalHostIP0[] localHostIP0Field;

            private LocalHostMask0[] localHostMask0Field;

            private LocalHostGW0[] localHostGW0Field;

            private CcmFirstNode[] ccmFirstNodeField;

            private IPSecFirstNode[] iPSecFirstNodeField;

            private SftpPwCrypt[] sftpPwCryptField;

            private IPSecSecurityPwCrypt[] iPSecSecurityPwCryptField;

            private LocalHostTimezone[] localHostTimezoneField;

            private CertX509[] certX509Field;

            private LocalHostAdminName[] localHostAdminNameField;

            private LocalHostAdminUIDValue[] localHostAdminUIDValueField;

            private LocalHostAdminPwCrypt[] localHostAdminPwCryptField;

            private ReencryptFlag[] reencryptFlagField;

            private ValidateNetworkingBypass[] validateNetworkingBypassField;

            private ApplUserUsername[] applUserUsernameField;

            private ApplUserPwCrypt[] applUserPwCryptField;

            private CallHomeDisable[] callHomeDisableField;

            private ApplUserDbPwCrypt[] applUserDbPwCryptField;

            private NtpServer[] ntpServerField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Version
            {
                get
                {
                    return this.versionField;
                }
                set
                {
                    this.versionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("InstallType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public InstallType[] InstallType
            {
                get
                {
                    return this.installTypeField;
                }
                set
                {
                    this.installTypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ProductDeployment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ProductDeployment[] ProductDeployment
            {
                get
                {
                    return this.productDeploymentField;
                }
                set
                {
                    this.productDeploymentField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("PlatformConfigurationDone", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformConfigurationDone[] PlatformConfigurationDone
            {
                get
                {
                    return this.platformConfigurationDoneField;
                }
                set
                {
                    this.platformConfigurationDoneField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("PreLoadedSoftware", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PreLoadedSoftware[] PreLoadedSoftware
            {
                get
                {
                    return this.preLoadedSoftwareField;
                }
                set
                {
                    this.preLoadedSoftwareField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostName[] LocalHostName
            {
                get
                {
                    return this.localHostNameField;
                }
                set
                {
                    this.localHostNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostNICAuto", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostNICAuto[] LocalHostNICAuto
            {
                get
                {
                    return this.localHostNICAutoField;
                }
                set
                {
                    this.localHostNICAutoField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ChangeMTUSize", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ChangeMTUSize[] ChangeMTUSize
            {
                get
                {
                    return this.changeMTUSizeField;
                }
                set
                {
                    this.changeMTUSizeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostDHCP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostDHCP[] LocalHostDHCP
            {
                get
                {
                    return this.localHostDHCPField;
                }
                set
                {
                    this.localHostDHCPField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostDomain", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostDomain[] LocalHostDomain
            {
                get
                {
                    return this.localHostDomainField;
                }
                set
                {
                    this.localHostDomainField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostIP0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostIP0[] LocalHostIP0
            {
                get
                {
                    return this.localHostIP0Field;
                }
                set
                {
                    this.localHostIP0Field = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostMask0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostMask0[] LocalHostMask0
            {
                get
                {
                    return this.localHostMask0Field;
                }
                set
                {
                    this.localHostMask0Field = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostGW0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostGW0[] LocalHostGW0
            {
                get
                {
                    return this.localHostGW0Field;
                }
                set
                {
                    this.localHostGW0Field = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("CcmFirstNode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public CcmFirstNode[] CcmFirstNode
            {
                get
                {
                    return this.ccmFirstNodeField;
                }
                set
                {
                    this.ccmFirstNodeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("IPSecFirstNode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public IPSecFirstNode[] IPSecFirstNode
            {
                get
                {
                    return this.iPSecFirstNodeField;
                }
                set
                {
                    this.iPSecFirstNodeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("SftpPwCrypt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public SftpPwCrypt[] SftpPwCrypt
            {
                get
                {
                    return this.sftpPwCryptField;
                }
                set
                {
                    this.sftpPwCryptField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("IPSecSecurityPwCrypt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public IPSecSecurityPwCrypt[] IPSecSecurityPwCrypt
            {
                get
                {
                    return this.iPSecSecurityPwCryptField;
                }
                set
                {
                    this.iPSecSecurityPwCryptField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostTimezone", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostTimezone[] LocalHostTimezone
            {
                get
                {
                    return this.localHostTimezoneField;
                }
                set
                {
                    this.localHostTimezoneField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("CertX509", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public CertX509[] CertX509
            {
                get
                {
                    return this.certX509Field;
                }
                set
                {
                    this.certX509Field = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostAdminName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostAdminName[] LocalHostAdminName
            {
                get
                {
                    return this.localHostAdminNameField;
                }
                set
                {
                    this.localHostAdminNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostAdminUIDValue", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostAdminUIDValue[] LocalHostAdminUIDValue
            {
                get
                {
                    return this.localHostAdminUIDValueField;
                }
                set
                {
                    this.localHostAdminUIDValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("LocalHostAdminPwCrypt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public LocalHostAdminPwCrypt[] LocalHostAdminPwCrypt
            {
                get
                {
                    return this.localHostAdminPwCryptField;
                }
                set
                {
                    this.localHostAdminPwCryptField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ReencryptFlag", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ReencryptFlag[] ReencryptFlag
            {
                get
                {
                    return this.reencryptFlagField;
                }
                set
                {
                    this.reencryptFlagField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ValidateNetworkingBypass", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ValidateNetworkingBypass[] ValidateNetworkingBypass
            {
                get
                {
                    return this.validateNetworkingBypassField;
                }
                set
                {
                    this.validateNetworkingBypassField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ApplUserUsername", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ApplUserUsername[] ApplUserUsername
            {
                get
                {
                    return this.applUserUsernameField;
                }
                set
                {
                    this.applUserUsernameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ApplUserPwCrypt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ApplUserPwCrypt[] ApplUserPwCrypt
            {
                get
                {
                    return this.applUserPwCryptField;
                }
                set
                {
                    this.applUserPwCryptField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("CallHomeDisable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public CallHomeDisable[] CallHomeDisable
            {
                get
                {
                    return this.callHomeDisableField;
                }
                set
                {
                    this.callHomeDisableField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ApplUserDbPwCrypt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public ApplUserDbPwCrypt[] ApplUserDbPwCrypt
            {
                get
                {
                    return this.applUserDbPwCryptField;
                }
                set
                {
                    this.applUserDbPwCryptField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("NtpServer", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public NtpServer[] NtpServer
            {
                get
                {
                    return this.ntpServerField;
                }
                set
                {
                    this.ntpServerField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class InstallType
        {

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProductDeployment
        {

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformConfigurationDone
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PreLoadedSoftware
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostName
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostNICAuto
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ChangeMTUSize
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostDHCP
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostDomain
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostIP0
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostMask0
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostGW0
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class CcmFirstNode
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class IPSecFirstNode
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SftpPwCrypt
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class IPSecSecurityPwCrypt
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostTimezone
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class CertX509
        {

            private PlatformDataCertX509Org[] orgField;

            private PlatformDataCertX509Unit[] unitField;

            private PlatformDataCertX509Location[] locationField;

            private PlatformDataCertX509State[] stateField;

            private PlatformDataCertX509Country[] countryField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Org", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformDataCertX509Org[] Org
            {
                get
                {
                    return this.orgField;
                }
                set
                {
                    this.orgField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Unit", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformDataCertX509Unit[] Unit
            {
                get
                {
                    return this.unitField;
                }
                set
                {
                    this.unitField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Location", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformDataCertX509Location[] Location
            {
                get
                {
                    return this.locationField;
                }
                set
                {
                    this.locationField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("State", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformDataCertX509State[] State
            {
                get
                {
                    return this.stateField;
                }
                set
                {
                    this.stateField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Country", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public PlatformDataCertX509Country[] Country
            {
                get
                {
                    return this.countryField;
                }
                set
                {
                    this.countryField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformDataCertX509Org
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformDataCertX509Unit
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformDataCertX509Location
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformDataCertX509State
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class PlatformDataCertX509Country
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostAdminName
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostAdminUIDValue
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LocalHostAdminPwCrypt
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ReencryptFlag
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ValidateNetworkingBypass
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ApplUserUsername
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ApplUserPwCrypt
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class CallHomeDisable
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ApplUserDbPwCrypt
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class NtpServer
        {

            private string paramNameTextField;

            private string paramDefaultValueField;

            private string paramValueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamNameText
            {
                get
                {
                    return this.paramNameTextField;
                }
                set
                {
                    this.paramNameTextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamDefaultValue
            {
                get
                {
                    return this.paramDefaultValueField;
                }
                set
                {
                    this.paramDefaultValueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ParamValue
            {
                get
                {
                    return this.paramValueField;
                }
                set
                {
                    this.paramValueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class NewDataSet
        {

            private PlatformData[] itemsField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("PlatformData")]
            public PlatformData[] Items
            {
                get
                {
                    return this.itemsField;
                }
                set
                {
                    this.itemsField = value;
                }
            }
        }
    }
}