using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace ADHDTech.UCOSClients
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.8762
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by wsdl, Version=2.0.50727.3038.
    // 

    public class BruteForcePolicy : System.Net.ICertificatePolicy
    {
        public bool CheckValidationResult(System.Net.ServicePoint sp, System.Security.Cryptography.X509Certificates.X509Certificate cert,
                System.Net.WebRequest request, int problem)
        {
            return true;
        }
    }



    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public abstract partial class APIResponse
    {

        private ulong sequenceField;

        private bool sequenceFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequenceSpecified
        {
            get
            {
                return this.sequenceFieldSpecified;
            }
            set
            {
                this.sequenceFieldSpecified = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class ExecuteSQLUpdateRes : APIResponse
    {

        private ExecuteSQLUpdateResReturn returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExecuteSQLUpdateResReturn @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class ExecuteSQLUpdateResReturn
    {

        private string rowsUpdatedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string rowsUpdated
        {
            get
            {
                return this.rowsUpdatedField;
            }
            set
            {
                this.rowsUpdatedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class ExecuteSQLQueryRes : APIResponse
    {

        private object[] returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public object[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void doAuthenticateUserCompletedEventHandler(object sender, doAuthenticateUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doAuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal doAuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class AXLError
    {

        private int axlcodeField;

        private string axlmessageField;

        private string requestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int axlcode
        {
            get
            {
                return this.axlcodeField;
            }
            set
            {
                this.axlcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string axlmessage
        {
            get
            {
                return this.axlmessageField;
            }
            set
            {
                this.axlmessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "AXLAPIBinding", Namespace = "http://www.cisco.com/AXLAPIService/")]

    public partial class AXLAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback executeSQLQueryOperationCompleted;

        private System.Threading.SendOrPostCallback executeSQLUpdateOperationCompleted;

        private System.Threading.SendOrPostCallback doAuthenticateUserOperationCompleted;

        /// <remarks/>
        public AXLAPIService(string ccmIp, string user, string password)
        {
            System.Net.ServicePointManager.CertificatePolicy = new BruteForcePolicy();

            this.Url = "https://" + ccmIp + ":8443/axl/";
            this.Credentials = new System.Net.NetworkCredential(user, password);
        }

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.HttpWebRequest request = base.GetWebRequest(uri) as System.Net.HttpWebRequest;
            request.ProtocolVersion = System.Net.HttpVersion.Version10;

            return request;
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
        public delegate void executeSQLQueryCompletedEventHandler(object sender, executeSQLQueryCompletedEventArgs e);

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        public partial class executeSQLQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            internal executeSQLQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState)
            {
                this.results = results;
            }

            /// <remarks/>
            public ExecuteSQLQueryRes Result
            {
                get
                {
                    this.RaiseExceptionIfNecessary();
                    return ((ExecuteSQLQueryRes)(this.results[0]));
                }
            }
        }


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
        public delegate void executeSQLUpdateCompletedEventHandler(object sender, executeSQLUpdateCompletedEventArgs e);

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        public partial class executeSQLUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            internal executeSQLUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState)
            {
                this.results = results;
            }

            /// <remarks/>
            public ExecuteSQLUpdateRes Result
            {
                get
                {
                    this.RaiseExceptionIfNecessary();
                    return ((ExecuteSQLUpdateRes)(this.results[0]));
                }
            }
        }


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
        public delegate void doAuthenticateUserCompletedEventHandler(object sender, doAuthenticateUserCompletedEventArgs e);


        /// <remarks/>
        public event executeSQLQueryCompletedEventHandler executeSQLQueryCompleted;

        /// <remarks/>
        public event executeSQLUpdateCompletedEventHandler executeSQLUpdateCompleted;

        /// <remarks/>
        public event doAuthenticateUserCompletedEventHandler doAuthenticateUserCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CUCM:DB ver=10.5 executeSQLQuery", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("executeSQLQueryResponse", Namespace = "http://www.cisco.com/AXL/API/10.5")]
        public ExecuteSQLQueryRes executeSQLQuery([System.Xml.Serialization.XmlElementAttribute("executeSQLQuery", Namespace = "http://www.cisco.com/AXL/API/10.5")] ExecuteSQLQueryReq executeSQLQuery1)
        {
            object[] results = this.Invoke("executeSQLQuery", new object[] {
                    executeSQLQuery1});
            return ((ExecuteSQLQueryRes)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginexecuteSQLQuery(ExecuteSQLQueryReq executeSQLQuery1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("executeSQLQuery", new object[] {
                    executeSQLQuery1}, callback, asyncState);
        }

        /// <remarks/>
        public ExecuteSQLQueryRes EndexecuteSQLQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ExecuteSQLQueryRes)(results[0]));
        }

        /// <remarks/>
        public void executeSQLQueryAsync(ExecuteSQLQueryReq executeSQLQuery1)
        {
            this.executeSQLQueryAsync(executeSQLQuery1, null);
        }

        /// <remarks/>
        public void executeSQLQueryAsync(ExecuteSQLQueryReq executeSQLQuery1, object userState)
        {
            if ((this.executeSQLQueryOperationCompleted == null))
            {
                this.executeSQLQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteSQLQueryOperationCompleted);
            }
            this.InvokeAsync("executeSQLQuery", new object[] {
                    executeSQLQuery1}, this.executeSQLQueryOperationCompleted, userState);
        }

        private void OnexecuteSQLQueryOperationCompleted(object arg)
        {
            if ((this.executeSQLQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeSQLQueryCompleted(this, new executeSQLQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CUCM:DB ver=10.5 executeSQLUpdate", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("executeSQLUpdateResponse", Namespace = "http://www.cisco.com/AXL/API/10.5")]
        public ExecuteSQLUpdateRes executeSQLUpdate([System.Xml.Serialization.XmlElementAttribute("executeSQLUpdate", Namespace = "http://www.cisco.com/AXL/API/10.5")] ExecuteSQLUpdateReq executeSQLUpdate1)
        {
            object[] results = this.Invoke("executeSQLUpdate", new object[] {
                    executeSQLUpdate1});
            return ((ExecuteSQLUpdateRes)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginexecuteSQLUpdate(ExecuteSQLUpdateReq executeSQLUpdate1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("executeSQLUpdate", new object[] {
                    executeSQLUpdate1}, callback, asyncState);
        }

        /// <remarks/>
        public ExecuteSQLUpdateRes EndexecuteSQLUpdate(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ExecuteSQLUpdateRes)(results[0]));
        }

        /// <remarks/>
        public void executeSQLUpdateAsync(ExecuteSQLUpdateReq executeSQLUpdate1)
        {
            this.executeSQLUpdateAsync(executeSQLUpdate1, null);
        }

        /// <remarks/>
        public void executeSQLUpdateAsync(ExecuteSQLUpdateReq executeSQLUpdate1, object userState)
        {
            if ((this.executeSQLUpdateOperationCompleted == null))
            {
                this.executeSQLUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteSQLUpdateOperationCompleted);
            }
            this.InvokeAsync("executeSQLUpdate", new object[] {
                    executeSQLUpdate1}, this.executeSQLUpdateOperationCompleted, userState);
        }

        private void OnexecuteSQLUpdateOperationCompleted(object arg)
        {
            if ((this.executeSQLUpdateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeSQLUpdateCompleted(this, new executeSQLUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public abstract partial class APIRequest
    {

        private ulong sequenceField;

        private bool sequenceFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequenceSpecified
        {
            get
            {
                return this.sequenceFieldSpecified;
            }
            set
            {
                this.sequenceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class ExecuteSQLUpdateReq : APIRequest
    {

        private string sqlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sql
        {
            get
            {
                return this.sqlField;
            }
            set
            {
                this.sqlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cisco.com/AXL/API/10.5")]
    public partial class ExecuteSQLQueryReq : APIRequest
    {

        private string sqlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sql
        {
            get
            {
                return this.sqlField;
            }
            set
            {
                this.sqlField = value;
            }
        }
    }


}
