using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace ADHDTech.UCOSClients
{

    // 
    // This source code was auto-generated by wsdl, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "RisBinding", Namespace = "http://schemas.cisco.com/ast/soap/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CmDevSingleLineStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CmDeviceSIP))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CmNodeSIP))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ServerInformation))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ColumnValueType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ColumnType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CtiItem))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CtiNode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SelectDirNumber))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SelectDevName))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SelectAppItem))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CmDevice))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CmNode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SelectItem))]
    public partial class RISService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private AstHeader astHeaderValueField;

        private System.Threading.SendOrPostCallback SelectCmDeviceOperationCompleted;

        private System.Threading.SendOrPostCallback SelectCtiItemOperationCompleted;

        private System.Threading.SendOrPostCallback ExecuteCCMSQLStatementOperationCompleted;

        private System.Threading.SendOrPostCallback GetServerInfoOperationCompleted;

        private System.Threading.SendOrPostCallback SelectCmDeviceSIPOperationCompleted;

        /// <remarks/>
        public RISService(string ccmIp, string user, string password)
        {
            System.Net.ServicePointManager.CertificatePolicy = new BruteForcePolicy();

            this.Url = "https://" + ccmIp + ":8443/realtimeservice/services/RisPort";
            this.Credentials = new System.Net.NetworkCredential(user, password);
        }

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.HttpWebRequest request = base.GetWebRequest(uri) as System.Net.HttpWebRequest;
            //request.ProtocolVersion = System.Net.HttpVersion.Version10;
            request.Proxy = new System.Net.WebProxy();

            return request;
        }

        public AstHeader AstHeaderValue
        {
            get
            {
                return this.astHeaderValueField;
            }
            set
            {
                this.astHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event SelectCmDeviceCompletedEventHandler SelectCmDeviceCompleted;

        /// <remarks/>
        public event SelectCtiItemCompletedEventHandler SelectCtiItemCompleted;

        /// <remarks/>
        public event ExecuteCCMSQLStatementCompletedEventHandler ExecuteCCMSQLStatementCompleted;

        /// <remarks/>
        public event GetServerInfoCompletedEventHandler GetServerInfoCompleted;

        /// <remarks/>
        public event SelectCmDeviceSIPCompletedEventHandler SelectCmDeviceSIPCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AstHeaderValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.cisco.com/ast/soap/action/#RisPort#SelectCmDevice", RequestNamespace = "http://schemas.cisco.com/ast/soap/", ResponseNamespace = "http://schemas.cisco.com/ast/soap/")]
        public SelectCmDeviceResult SelectCmDevice(ref string StateInfo, CmSelectionCriteria CmSelectionCriteria)
        {
            object[] results = this.Invoke("SelectCmDevice", new object[] {
                    StateInfo,
                    CmSelectionCriteria});
            StateInfo = ((string)(results[1]));
            return ((SelectCmDeviceResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSelectCmDevice(string StateInfo, CmSelectionCriteria CmSelectionCriteria, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SelectCmDevice", new object[] {
                    StateInfo,
                    CmSelectionCriteria}, callback, asyncState);
        }

        /// <remarks/>
        public SelectCmDeviceResult EndSelectCmDevice(System.IAsyncResult asyncResult, out string StateInfo)
        {
            object[] results = this.EndInvoke(asyncResult);
            StateInfo = ((string)(results[1]));
            return ((SelectCmDeviceResult)(results[0]));
        }

        /// <remarks/>
        public void SelectCmDeviceAsync(string StateInfo, CmSelectionCriteria CmSelectionCriteria)
        {
            this.SelectCmDeviceAsync(StateInfo, CmSelectionCriteria, null);
        }

        /// <remarks/>
        public void SelectCmDeviceAsync(string StateInfo, CmSelectionCriteria CmSelectionCriteria, object userState)
        {
            if ((this.SelectCmDeviceOperationCompleted == null))
            {
                this.SelectCmDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCmDeviceOperationCompleted);
            }
            this.InvokeAsync("SelectCmDevice", new object[] {
                    StateInfo,
                    CmSelectionCriteria}, this.SelectCmDeviceOperationCompleted, userState);
        }

        private void OnSelectCmDeviceOperationCompleted(object arg)
        {
            if ((this.SelectCmDeviceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCmDeviceCompleted(this, new SelectCmDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AstHeaderValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.cisco.com/ast/soap/action/#RisPort#SelectCtiItem", RequestNamespace = "http://schemas.cisco.com/ast/soap/", ResponseNamespace = "http://schemas.cisco.com/ast/soap/")]
        public SelectCtiItemResult SelectCtiItem(ref string StateInfo, CtiSelectionCriteria CtiSelectionCriteria)
        {
            object[] results = this.Invoke("SelectCtiItem", new object[] {
                    StateInfo,
                    CtiSelectionCriteria});
            StateInfo = ((string)(results[1]));
            return ((SelectCtiItemResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSelectCtiItem(string StateInfo, CtiSelectionCriteria CtiSelectionCriteria, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SelectCtiItem", new object[] {
                    StateInfo,
                    CtiSelectionCriteria}, callback, asyncState);
        }

        /// <remarks/>
        public SelectCtiItemResult EndSelectCtiItem(System.IAsyncResult asyncResult, out string StateInfo)
        {
            object[] results = this.EndInvoke(asyncResult);
            StateInfo = ((string)(results[1]));
            return ((SelectCtiItemResult)(results[0]));
        }

        /// <remarks/>
        public void SelectCtiItemAsync(string StateInfo, CtiSelectionCriteria CtiSelectionCriteria)
        {
            this.SelectCtiItemAsync(StateInfo, CtiSelectionCriteria, null);
        }

        /// <remarks/>
        public void SelectCtiItemAsync(string StateInfo, CtiSelectionCriteria CtiSelectionCriteria, object userState)
        {
            if ((this.SelectCtiItemOperationCompleted == null))
            {
                this.SelectCtiItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCtiItemOperationCompleted);
            }
            this.InvokeAsync("SelectCtiItem", new object[] {
                    StateInfo,
                    CtiSelectionCriteria}, this.SelectCtiItemOperationCompleted, userState);
        }

        private void OnSelectCtiItemOperationCompleted(object arg)
        {
            if ((this.SelectCtiItemCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCtiItemCompleted(this, new SelectCtiItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AstHeaderValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.cisco.com/ast/soap/action/#PerfmonPort#ExecuteCCMSQLStatement", RequestNamespace = "http://schemas.cisco.com/ast/soap/", ResponseNamespace = "http://schemas.cisco.com/ast/soap/")]
        [return: System.Xml.Serialization.SoapElementAttribute("ExcuteSQLOutputData")]
        public ColumnValueType[] ExecuteCCMSQLStatement(string ExecuteSQLInputData, ColumnType[] GetColumns)
        {
            object[] results = this.Invoke("ExecuteCCMSQLStatement", new object[] {
                    ExecuteSQLInputData,
                    GetColumns});
            return ((ColumnValueType[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExecuteCCMSQLStatement(string ExecuteSQLInputData, ColumnType[] GetColumns, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ExecuteCCMSQLStatement", new object[] {
                    ExecuteSQLInputData,
                    GetColumns}, callback, asyncState);
        }

        /// <remarks/>
        public ColumnValueType[] EndExecuteCCMSQLStatement(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ColumnValueType[])(results[0]));
        }

        /// <remarks/>
        public void ExecuteCCMSQLStatementAsync(string ExecuteSQLInputData, ColumnType[] GetColumns)
        {
            this.ExecuteCCMSQLStatementAsync(ExecuteSQLInputData, GetColumns, null);
        }

        /// <remarks/>
        public void ExecuteCCMSQLStatementAsync(string ExecuteSQLInputData, ColumnType[] GetColumns, object userState)
        {
            if ((this.ExecuteCCMSQLStatementOperationCompleted == null))
            {
                this.ExecuteCCMSQLStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteCCMSQLStatementOperationCompleted);
            }
            this.InvokeAsync("ExecuteCCMSQLStatement", new object[] {
                    ExecuteSQLInputData,
                    GetColumns}, this.ExecuteCCMSQLStatementOperationCompleted, userState);
        }

        private void OnExecuteCCMSQLStatementOperationCompleted(object arg)
        {
            if ((this.ExecuteCCMSQLStatementCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCCMSQLStatementCompleted(this, new ExecuteCCMSQLStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AstHeaderValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.cisco.com/ast/soap/action/#PerfmonPort#GetServerInfo", RequestNamespace = "http://schemas.cisco.com/ast/soap/", ResponseNamespace = "http://schemas.cisco.com/ast/soap/")]
        [return: System.Xml.Serialization.SoapElementAttribute("ServerInfo")]
        public ServerInformation[] GetServerInfo(string[] Hosts)
        {
            object[] results = this.Invoke("GetServerInfo", new object[] {
                    Hosts});
            return ((ServerInformation[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetServerInfo(string[] Hosts, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetServerInfo", new object[] {
                    Hosts}, callback, asyncState);
        }

        /// <remarks/>
        public ServerInformation[] EndGetServerInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ServerInformation[])(results[0]));
        }

        /// <remarks/>
        public void GetServerInfoAsync(string[] Hosts)
        {
            this.GetServerInfoAsync(Hosts, null);
        }

        /// <remarks/>
        public void GetServerInfoAsync(string[] Hosts, object userState)
        {
            if ((this.GetServerInfoOperationCompleted == null))
            {
                this.GetServerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerInfoOperationCompleted);
            }
            this.InvokeAsync("GetServerInfo", new object[] {
                    Hosts}, this.GetServerInfoOperationCompleted, userState);
        }

        private void OnGetServerInfoOperationCompleted(object arg)
        {
            if ((this.GetServerInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerInfoCompleted(this, new GetServerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AstHeaderValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.cisco.com/ast/soap/action/#RisPort#SelectCmDeviceSIP", RequestNamespace = "http://schemas.cisco.com/ast/soap/", ResponseNamespace = "http://schemas.cisco.com/ast/soap/")]
        [return: System.Xml.Serialization.SoapElementAttribute("SelectCmDeviceResultSIP")]
        public SelectCmDeviceResultSIP SelectCmDeviceSIP(ref string StateInfo, CmSelectionCriteriaSIP CmSelectionCriteriaSIP)
        {
            object[] results = this.Invoke("SelectCmDeviceSIP", new object[] {
                    StateInfo,
                    CmSelectionCriteriaSIP});
            StateInfo = ((string)(results[1]));
            return ((SelectCmDeviceResultSIP)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSelectCmDeviceSIP(string StateInfo, CmSelectionCriteriaSIP CmSelectionCriteriaSIP, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SelectCmDeviceSIP", new object[] {
                    StateInfo,
                    CmSelectionCriteriaSIP}, callback, asyncState);
        }

        /// <remarks/>
        public SelectCmDeviceResultSIP EndSelectCmDeviceSIP(System.IAsyncResult asyncResult, out string StateInfo)
        {
            object[] results = this.EndInvoke(asyncResult);
            StateInfo = ((string)(results[1]));
            return ((SelectCmDeviceResultSIP)(results[0]));
        }

        /// <remarks/>
        public void SelectCmDeviceSIPAsync(string StateInfo, CmSelectionCriteriaSIP CmSelectionCriteriaSIP)
        {
            this.SelectCmDeviceSIPAsync(StateInfo, CmSelectionCriteriaSIP, null);
        }

        /// <remarks/>
        public void SelectCmDeviceSIPAsync(string StateInfo, CmSelectionCriteriaSIP CmSelectionCriteriaSIP, object userState)
        {
            if ((this.SelectCmDeviceSIPOperationCompleted == null))
            {
                this.SelectCmDeviceSIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCmDeviceSIPOperationCompleted);
            }
            this.InvokeAsync("SelectCmDeviceSIP", new object[] {
                    StateInfo,
                    CmSelectionCriteriaSIP}, this.SelectCmDeviceSIPOperationCompleted, userState);
        }

        private void OnSelectCmDeviceSIPOperationCompleted(object arg)
        {
            if ((this.SelectCmDeviceSIPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCmDeviceSIPCompleted(this, new SelectCmDeviceSIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class AstHeader : SoapHeader
    {

        private string sessionIdField;

        /// <remarks/>
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmDevSingleLineStatus
    {

        private string directoryNumberField;

        private CmSingleLineStatus statusField;

        /// <remarks/>
        public string DirectoryNumber
        {
            get
            {
                return this.directoryNumberField;
            }
            set
            {
                this.directoryNumberField = value;
            }
        }

        /// <remarks/>
        public CmSingleLineStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CmSingleLineStatus
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        Registered,

        /// <remarks/>
        UnRegistered,

        /// <remarks/>
        Rejected,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmDeviceSIP
    {

        private string nameField;

        private string ipAddressField;

        private string dirNumberField;

        private System.Nullable<DeviceClass> classField;

        private System.Nullable<uint> modelField;

        private System.Nullable<uint> productField;

        private System.Nullable<uint> boxProductField;

        private System.Nullable<CmDevHttpd> httpdField;

        private uint registrationAttemptsField;

        private bool isCtiControllableField;

        private string loginUserIdField;

        private CmDevRegStat statusField;

        private System.Nullable<uint> statusReasonField;

        private System.Nullable<uint> perfMonObjectField;

        private System.Nullable<uint> dChannelField;

        private string descriptionField;

        private H323Trunk h323TrunkField;

        private System.Nullable<uint> timeStampField;

        private ProtocolType protocolField;

        private uint numOfLinesField;

        private CmDevSingleLineStatus[] linesStatusField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string IpAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string DirNumber
        {
            get
            {
                return this.dirNumberField;
            }
            set
            {
                this.dirNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<DeviceClass> Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> BoxProduct
        {
            get
            {
                return this.boxProductField;
            }
            set
            {
                this.boxProductField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CmDevHttpd> Httpd
        {
            get
            {
                return this.httpdField;
            }
            set
            {
                this.httpdField = value;
            }
        }

        /// <remarks/>
        public uint RegistrationAttempts
        {
            get
            {
                return this.registrationAttemptsField;
            }
            set
            {
                this.registrationAttemptsField = value;
            }
        }

        /// <remarks/>
        public bool IsCtiControllable
        {
            get
            {
                return this.isCtiControllableField;
            }
            set
            {
                this.isCtiControllableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string LoginUserId
        {
            get
            {
                return this.loginUserIdField;
            }
            set
            {
                this.loginUserIdField = value;
            }
        }

        /// <remarks/>
        public CmDevRegStat Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> StatusReason
        {
            get
            {
                return this.statusReasonField;
            }
            set
            {
                this.statusReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> PerfMonObject
        {
            get
            {
                return this.perfMonObjectField;
            }
            set
            {
                this.perfMonObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> DChannel
        {
            get
            {
                return this.dChannelField;
            }
            set
            {
                this.dChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public H323Trunk H323Trunk
        {
            get
            {
                return this.h323TrunkField;
            }
            set
            {
                this.h323TrunkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }

        /// <remarks/>
        public ProtocolType Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        public uint NumOfLines
        {
            get
            {
                return this.numOfLinesField;
            }
            set
            {
                this.numOfLinesField = value;
            }
        }

        /// <remarks/>
        public CmDevSingleLineStatus[] LinesStatus
        {
            get
            {
                return this.linesStatusField;
            }
            set
            {
                this.linesStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum DeviceClass
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        Phone,

        /// <remarks/>
        Gateway,

        /// <remarks/>
        H323,

        /// <remarks/>
        Cti,

        /// <remarks/>
        VoiceMail,

        /// <remarks/>
        MediaResources,

        /// <remarks/>
        Unknown,

        /// <remarks/>
        [System.Xml.Serialization.SoapEnumAttribute("SIP Trunk")]
        SIPTrunk,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CmDevHttpd
    {

        /// <remarks/>
        Yes,

        /// <remarks/>
        No,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CmDevRegStat
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        Registered,

        /// <remarks/>
        UnRegistered,

        /// <remarks/>
        Rejected,

        /// <remarks/>
        PartiallyRegistered,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class H323Trunk
    {

        private string configNameField;

        private string techPrefixField;

        private string zoneField;

        private string remoteCmServer1Field;

        private string remoteCmServer2Field;

        private string remoteCmServer3Field;

        private string altGkListField;

        private string activeGkField;

        private string callSignalAddrField;

        private string rasAddrField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string ConfigName
        {
            get
            {
                return this.configNameField;
            }
            set
            {
                this.configNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string TechPrefix
        {
            get
            {
                return this.techPrefixField;
            }
            set
            {
                this.techPrefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string RemoteCmServer1
        {
            get
            {
                return this.remoteCmServer1Field;
            }
            set
            {
                this.remoteCmServer1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string RemoteCmServer2
        {
            get
            {
                return this.remoteCmServer2Field;
            }
            set
            {
                this.remoteCmServer2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string RemoteCmServer3
        {
            get
            {
                return this.remoteCmServer3Field;
            }
            set
            {
                this.remoteCmServer3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string AltGkList
        {
            get
            {
                return this.altGkListField;
            }
            set
            {
                this.altGkListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string ActiveGk
        {
            get
            {
                return this.activeGkField;
            }
            set
            {
                this.activeGkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string CallSignalAddr
        {
            get
            {
                return this.callSignalAddrField;
            }
            set
            {
                this.callSignalAddrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string RasAddr
        {
            get
            {
                return this.rasAddrField;
            }
            set
            {
                this.rasAddrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum ProtocolType
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        SCCP,

        /// <remarks/>
        SIP,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmNodeSIP
    {

        private RisReturnCode returnCodeField;

        private string nameField;

        private bool noChangeField;

        private CmDeviceSIP[] cmDevicesField;

        /// <remarks/>
        public RisReturnCode ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public bool NoChange
        {
            get
            {
                return this.noChangeField;
            }
            set
            {
                this.noChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CmDeviceSIP[] CmDevices
        {
            get
            {
                return this.cmDevicesField;
            }
            set
            {
                this.cmDevicesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum RisReturnCode
    {

        /// <remarks/>
        Ok,

        /// <remarks/>
        NotFound,

        /// <remarks/>
        InvalidRequest,

        /// <remarks/>
        InternalError,

        /// <remarks/>
        NodeNotResponding,

        /// <remarks/>
        InvalidNodeName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectCmDeviceResultSIP
    {

        private uint totalDevicesFoundField;

        private CmNodeSIP[] cmNodesField;

        /// <remarks/>
        public uint TotalDevicesFound
        {
            get
            {
                return this.totalDevicesFoundField;
            }
            set
            {
                this.totalDevicesFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CmNodeSIP[] CmNodes
        {
            get
            {
                return this.cmNodesField;
            }
            set
            {
                this.cmNodesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmSelectionCriteriaSIP
    {

        private System.Nullable<uint> maxReturnedDevicesField;

        private string classField;

        private System.Nullable<uint> modelField;

        private string statusField;

        private string nodeNameField;

        private string selectByField;

        private SelectItem[] selectItemsField;

        private System.Nullable<ProtocolType> protocolField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> MaxReturnedDevices
        {
            get
            {
                return this.maxReturnedDevicesField;
            }
            set
            {
                this.maxReturnedDevicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string NodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }

        /// <remarks/>
        public string SelectBy
        {
            get
            {
                return this.selectByField;
            }
            set
            {
                this.selectByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SelectItem[] SelectItems
        {
            get
            {
                return this.selectItemsField;
            }
            set
            {
                this.selectItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<ProtocolType> Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectItem
    {

        private string itemField;

        /// <remarks/>
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class ServerInformation
    {

        private string hostNameField;

        private string osnameField;

        private string osversionField;

        private string osarchField;

        private string javaruntimeversionField;

        private string javavmvendorField;

        private string callmanagerversionField;

        private string active_VersionsField;

        private string in_Active_VersionsField;

        /// <remarks/>
        public string HostName
        {
            get
            {
                return this.hostNameField;
            }
            set
            {
                this.hostNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("os-name")]
        public string osname
        {
            get
            {
                return this.osnameField;
            }
            set
            {
                this.osnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("os-version")]
        public string osversion
        {
            get
            {
                return this.osversionField;
            }
            set
            {
                this.osversionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("os-arch")]
        public string osarch
        {
            get
            {
                return this.osarchField;
            }
            set
            {
                this.osarchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("java-runtime-version")]
        public string javaruntimeversion
        {
            get
            {
                return this.javaruntimeversionField;
            }
            set
            {
                this.javaruntimeversionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("java-vm-vendor")]
        public string javavmvendor
        {
            get
            {
                return this.javavmvendorField;
            }
            set
            {
                this.javavmvendorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("call-manager-version")]
        public string callmanagerversion
        {
            get
            {
                return this.callmanagerversionField;
            }
            set
            {
                this.callmanagerversionField = value;
            }
        }

        /// <remarks/>
        public string Active_Versions
        {
            get
            {
                return this.active_VersionsField;
            }
            set
            {
                this.active_VersionsField = value;
            }
        }

        /// <remarks/>
        public string In_Active_Versions
        {
            get
            {
                return this.in_Active_VersionsField;
            }
            set
            {
                this.in_Active_VersionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class ColumnValueType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class ColumnType
    {

        private string nameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CtiLine
    {

        private string dirNumberField;

        private CtiStatus lineStatusField;

        private uint lineStatusReasonField;

        private uint lineTimeStampField;

        /// <remarks/>
        public string DirNumber
        {
            get
            {
                return this.dirNumberField;
            }
            set
            {
                this.dirNumberField = value;
            }
        }

        /// <remarks/>
        public CtiStatus LineStatus
        {
            get
            {
                return this.lineStatusField;
            }
            set
            {
                this.lineStatusField = value;
            }
        }

        /// <remarks/>
        public uint LineStatusReason
        {
            get
            {
                return this.lineStatusReasonField;
            }
            set
            {
                this.lineStatusReasonField = value;
            }
        }

        /// <remarks/>
        public uint LineTimeStamp
        {
            get
            {
                return this.lineTimeStampField;
            }
            set
            {
                this.lineTimeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CtiStatus
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        Open,

        /// <remarks/>
        Closed,

        /// <remarks/>
        OpenFailed,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CtiDevice
    {

        private System.Nullable<bool> appControlsMediaField;

        private string deviceNameField;

        private System.Nullable<CtiStatus> deviceStatusField;

        private System.Nullable<uint> deviceStatusReasonField;

        private System.Nullable<uint> deviceTimeStampField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<bool> AppControlsMedia
        {
            get
            {
                return this.appControlsMediaField;
            }
            set
            {
                this.appControlsMediaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string DeviceName
        {
            get
            {
                return this.deviceNameField;
            }
            set
            {
                this.deviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CtiStatus> DeviceStatus
        {
            get
            {
                return this.deviceStatusField;
            }
            set
            {
                this.deviceStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> DeviceStatusReason
        {
            get
            {
                return this.deviceStatusReasonField;
            }
            set
            {
                this.deviceStatusReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> DeviceTimeStamp
        {
            get
            {
                return this.deviceTimeStampField;
            }
            set
            {
                this.deviceTimeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CtiItem
    {

        private string appIdField;

        private string userIdField;

        private string appIpAddrField;

        private System.Nullable<CtiStatus> appStatusField;

        private System.Nullable<uint> appStatusReasonField;

        private System.Nullable<uint> appTimeStampField;

        private CtiDevice ctiDeviceField;

        private CtiLine ctiLineField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string AppId
        {
            get
            {
                return this.appIdField;
            }
            set
            {
                this.appIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string AppIpAddr
        {
            get
            {
                return this.appIpAddrField;
            }
            set
            {
                this.appIpAddrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CtiStatus> AppStatus
        {
            get
            {
                return this.appStatusField;
            }
            set
            {
                this.appStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> AppStatusReason
        {
            get
            {
                return this.appStatusReasonField;
            }
            set
            {
                this.appStatusReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> AppTimeStamp
        {
            get
            {
                return this.appTimeStampField;
            }
            set
            {
                this.appTimeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CtiDevice CtiDevice
        {
            get
            {
                return this.ctiDeviceField;
            }
            set
            {
                this.ctiDeviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CtiLine CtiLine
        {
            get
            {
                return this.ctiLineField;
            }
            set
            {
                this.ctiLineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CtiNode
    {

        private RisReturnCode returnCodeField;

        private string nameField;

        private bool noChangeField;

        private CtiItem[] ctiItemsField;

        /// <remarks/>
        public RisReturnCode ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public bool NoChange
        {
            get
            {
                return this.noChangeField;
            }
            set
            {
                this.noChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CtiItem[] CtiItems
        {
            get
            {
                return this.ctiItemsField;
            }
            set
            {
                this.ctiItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectCtiItemResult
    {

        private uint totalItemsFoundField;

        private CtiNode[] ctiNodesField;

        /// <remarks/>
        public uint TotalItemsFound
        {
            get
            {
                return this.totalItemsFoundField;
            }
            set
            {
                this.totalItemsFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CtiNode[] CtiNodes
        {
            get
            {
                return this.ctiNodesField;
            }
            set
            {
                this.ctiNodesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectDirNumber
    {

        private string dirNumberField;

        /// <remarks/>
        public string DirNumber
        {
            get
            {
                return this.dirNumberField;
            }
            set
            {
                this.dirNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectDevName
    {

        private string devNameField;

        /// <remarks/>
        public string DevName
        {
            get
            {
                return this.devNameField;
            }
            set
            {
                this.devNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectAppItem
    {

        private string appItemField;

        /// <remarks/>
        public string AppItem
        {
            get
            {
                return this.appItemField;
            }
            set
            {
                this.appItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CtiSelectionCriteria
    {

        private System.Nullable<uint> maxReturnedItemsField;

        private System.Nullable<CtiMgrClass> ctiMgrClassField;

        private System.Nullable<CtiStatus> statusField;

        private string nodeNameField;

        private System.Nullable<CtiSelectAppBy> selectAppByField;

        private SelectAppItem[] appItemsField;

        private SelectDevName[] devNamesField;

        private SelectDirNumber[] dirNumbersField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> MaxReturnedItems
        {
            get
            {
                return this.maxReturnedItemsField;
            }
            set
            {
                this.maxReturnedItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CtiMgrClass> CtiMgrClass
        {
            get
            {
                return this.ctiMgrClassField;
            }
            set
            {
                this.ctiMgrClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CtiStatus> Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string NodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CtiSelectAppBy> SelectAppBy
        {
            get
            {
                return this.selectAppByField;
            }
            set
            {
                this.selectAppByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SelectAppItem[] AppItems
        {
            get
            {
                return this.appItemsField;
            }
            set
            {
                this.appItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SelectDevName[] DevNames
        {
            get
            {
                return this.devNamesField;
            }
            set
            {
                this.devNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SelectDirNumber[] DirNumbers
        {
            get
            {
                return this.dirNumbersField;
            }
            set
            {
                this.dirNumbersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CtiMgrClass
    {

        /// <remarks/>
        Provider,

        /// <remarks/>
        Device,

        /// <remarks/>
        Line,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public enum CtiSelectAppBy
    {

        /// <remarks/>
        AppId,

        /// <remarks/>
        AppIpAddress,

        /// <remarks/>
        UserId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmDevice
    {

        private string nameField;

        private string ipAddressField;

        private string dirNumberField;

        private System.Nullable<DeviceClass> classField;

        private System.Nullable<uint> modelField;

        private System.Nullable<uint> productField;

        private System.Nullable<uint> boxProductField;

        private System.Nullable<CmDevHttpd> httpdField;

        private uint registrationAttemptsField;

        private bool isCtiControllableField;

        private string loginUserIdField;

        private CmDevRegStat statusField;

        private System.Nullable<uint> statusReasonField;

        private System.Nullable<uint> perfMonObjectField;

        private System.Nullable<uint> dChannelField;

        private string descriptionField;

        private H323Trunk h323TrunkField;

        private System.Nullable<uint> timeStampField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string IpAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string DirNumber
        {
            get
            {
                return this.dirNumberField;
            }
            set
            {
                this.dirNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<DeviceClass> Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> BoxProduct
        {
            get
            {
                return this.boxProductField;
            }
            set
            {
                this.boxProductField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<CmDevHttpd> Httpd
        {
            get
            {
                return this.httpdField;
            }
            set
            {
                this.httpdField = value;
            }
        }

        /// <remarks/>
        public uint RegistrationAttempts
        {
            get
            {
                return this.registrationAttemptsField;
            }
            set
            {
                this.registrationAttemptsField = value;
            }
        }

        /// <remarks/>
        public bool IsCtiControllable
        {
            get
            {
                return this.isCtiControllableField;
            }
            set
            {
                this.isCtiControllableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string LoginUserId
        {
            get
            {
                return this.loginUserIdField;
            }
            set
            {
                this.loginUserIdField = value;
            }
        }

        /// <remarks/>
        public CmDevRegStat Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> StatusReason
        {
            get
            {
                return this.statusReasonField;
            }
            set
            {
                this.statusReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> PerfMonObject
        {
            get
            {
                return this.perfMonObjectField;
            }
            set
            {
                this.perfMonObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> DChannel
        {
            get
            {
                return this.dChannelField;
            }
            set
            {
                this.dChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public H323Trunk H323Trunk
        {
            get
            {
                return this.h323TrunkField;
            }
            set
            {
                this.h323TrunkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmNode
    {

        private RisReturnCode returnCodeField;

        private string nameField;

        private bool noChangeField;

        private CmDevice[] cmDevicesField;

        /// <remarks/>
        public RisReturnCode ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public bool NoChange
        {
            get
            {
                return this.noChangeField;
            }
            set
            {
                this.noChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CmDevice[] CmDevices
        {
            get
            {
                return this.cmDevicesField;
            }
            set
            {
                this.cmDevicesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class SelectCmDeviceResult
    {

        private uint totalDevicesFoundField;

        private CmNode[] cmNodesField;

        /// <remarks/>
        public uint TotalDevicesFound
        {
            get
            {
                return this.totalDevicesFoundField;
            }
            set
            {
                this.totalDevicesFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public CmNode[] CmNodes
        {
            get
            {
                return this.cmNodesField;
            }
            set
            {
                this.cmNodesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://schemas.cisco.com/ast/soap/")]
    public partial class CmSelectionCriteria
    {

        private System.Nullable<uint> maxReturnedDevicesField;

        private string classField;

        private System.Nullable<uint> modelField;

        private string statusField;

        private string nodeNameField;

        private string selectByField;

        private SelectItem[] selectItemsField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> MaxReturnedDevices
        {
            get
            {
                return this.maxReturnedDevicesField;
            }
            set
            {
                this.maxReturnedDevicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<uint> Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string NodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }

        /// <remarks/>
        public string SelectBy
        {
            get
            {
                return this.selectByField;
            }
            set
            {
                this.selectByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SelectItem[] SelectItems
        {
            get
            {
                return this.selectItemsField;
            }
            set
            {
                this.selectItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void SelectCmDeviceCompletedEventHandler(object sender, SelectCmDeviceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCmDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SelectCmDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SelectCmDeviceResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SelectCmDeviceResult)(this.results[0]));
            }
        }

        /// <remarks/>
        public string StateInfo
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void SelectCtiItemCompletedEventHandler(object sender, SelectCtiItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCtiItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SelectCtiItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SelectCtiItemResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SelectCtiItemResult)(this.results[0]));
            }
        }

        /// <remarks/>
        public string StateInfo
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ExecuteCCMSQLStatementCompletedEventHandler(object sender, ExecuteCCMSQLStatementCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCCMSQLStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExecuteCCMSQLStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ColumnValueType[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ColumnValueType[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void GetServerInfoCompletedEventHandler(object sender, GetServerInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetServerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ServerInformation[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ServerInformation[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void SelectCmDeviceSIPCompletedEventHandler(object sender, SelectCmDeviceSIPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCmDeviceSIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SelectCmDeviceSIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SelectCmDeviceResultSIP Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SelectCmDeviceResultSIP)(this.results[0]));
            }
        }

        /// <remarks/>
        public string StateInfo
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}
